# Настройка триггеров запуска. Анализ для master-ветки
trigger:
- master

# Задача запускается на self-hosted агенте из пула 'MyPool' 
pool: 'SHSH'

steps:
- task: CmdLine@2
  inputs:
    workingDirectory: "D:\\agent"
    script: |
      md .\PVSTestResults
      "C:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" -t "D:\agent\SonarSampleCs\SonarSampleCs.sln" -o D:\agent\PVSTestResults\TestTask.plog
      "C:\Program Files (x86)\PVS-Studio\PlogConverter.exe" -t html -o D:\agent\PVSTestResults\  D:\agent\PVSTestResults\TestTask.plog

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: D:\agent\PVSTestResults
    artifactName: PVSTestResults

- task : PowerShell@2
  inputs:
    targetType: 'inline'
    script:  |
      & "C:\Program Files (x86)\PVS-Studio\PlogConverter.exe" -t json -a GA:1 -o D:\agent\PVSTestResults\  D:\agent\PVSTestResults\TestTask.plog 
      IF (((Get-Content "D:\agent\PVSTestResults\TestTask.plog.json") |  ConvertFrom-Json).warnings.Count -eq 0)  {exit 0} ELSE {Write-Host "##vso[task.logissue type=error]Analys log contains High level warnings."; Write-Host "##vso[task.complete result=Failed;]" }
  
