# Настройка триггеров запуска. Анализ для master-ветки
trigger:
- master

# Задача запускается на self-hosted агенте из пула 'MyPool' 
pool: 'SHSH'

steps:
- task: CmdLine@2
  inputs:
    workingDirectory: "D:\\agent"
    script: |
      md .\PVSTestResults
      "C:\Program Files (x86)\PVS-Studio\PVS-Studio_Cmd.exe" -t "C:\Users\evtihevich\source\repos\SonarSampleCpp\SonarSampleCpp.sln" -o .\PVSTestResults\TestTask.plog
      "C:\Program Files (x86)\PVS-Studio\PlogConverter.exe" -t html -o .\PVSTestResults\ .\PVSTestResults\TestTask.plog
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: PVSTestResults
    artifactName: PVSTestResults
